### ISSUE TITLE
Topics migration fails becuase taxonomy_term_hierarchy no longer exists

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_legacy_migration#1]
This is more of an issue for Migrate Drupal 8 https://www.drupal.org/project/migrate_drupal_d8/issues/3026875
However worth noting here as the migration `migrate_plus.migration.topics.yml` will need to be updated.

**Comment by stephen-cox** [comment]
Rather than patching the module, ye seems that using the [d8_entity source plugin ](https://git.drupalcode.org/project/migrate_drupal_d8/-/blob/8.x-1.x/src/Plugin/migrate/source/d8/ContentEntity.php) solves this.
