### ISSUE TITLE
Migrate campaigns

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_legacy_migration#17]
Campaign paragraphs with direct mapping:

- Box link
- Call out box
- Fact box
- Link (aka Advanced Link)
- Link and summary
- Quote
- Text

Campaign paragraphs without a direct mapping:

- Text (two columns) - Need to migrate into 2 text paragraphs
- Text and image (50/50) - Need to migrate into a text and an image paragraph
- Video - New to migrate video URL into media entity (only 2 of these on Croydon site, none on BHCC)

Page builder paragraphs that are now redundant:

- Box link (Page builder)
- Call out box (Page builder)
- Fact boxes (Page builder)
- Link and summary (Page builder)
- Quote box (Page builder)

**Comment by stephen-cox** [comment]
@willguv @lbcwebmaster As discussed, this is the current numbers of paragraphs by type on the Croydon and BHCC sites

## Croydon


type | COUNT(*)
-- | --
advanced_links | 15
box_link | 25
box_link_page_builder_ | 27
call_out_box | 23
call_out_box_page_builder_ | 21
campaign_navigation | 7
contact | 17
fact_box | 26
fact_boxes_page_builder_ | 16
homepage_ia_blocks | 18
homepage_icons | 36
image_page_builder_ | 9
link_and_summary | 20
link_and_summary_page_builder_ | 14
newsroom_teasers | 4
pagebuilder_text | 1
quote | 4
quote_box_page_builder_ | 4
text | 5
text_and_image_50_50_ | 92
text_field_page_builder_ | 125
topic_list_builder | 71
video_page_builder_ | 2

## BHCC

type | COUNT(*)
-- | --
box_link | 58
box_link_page_builder_ | 27
call_out_box | 21
call_out_box_page_builder_ | 14
campaign_navigation | 2
column | 4
download | 436
fact_box | 65
fact_boxes_page_builder_ | 36
faq | 16
getting_on_better_box | 1
homepage_ia_blocks | 17
homepage_icons | 31
html_page_section | 241
link_and_summary | 51
link_and_summary_page_builder_ | 17
newsroom_teasers | 7
page_builder_layout | 8
quote | 25
quote_box_page_builder_ | 20
row | 4
text_and_image_50_50_ | 23
text_field_page_builder_ | 138
topic_list_builder | 275

**Comment by finnlewis** [comment]
The purposed of the above counts is to help BHCC and Croydon assess where to put effort into paragraph migrations that don't have an obvious one to one mapping.

**Comment by stephen-cox** [comment]
Code for this is on the [feature/16-campaigns-migration] branch. Current issues with this are on the pull request #23

**Comment by andybroomfield** [comment]
@stephen-cox Just to confirm, Page builder paragraphs that are now redundant: map onto Campaign paragraphs?
