### ISSUE TITLE
Split the migration into seperate groups

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_legacy_migration#24]
Currently the migration is run by executing `drush mim --group=localgov_migration`

This works fine to migrate the full site, however it will be useful to be able to take related content types together, particully if we do an alternative to full campaigns migration for our more complex campaigns.

**Comment by Adnan-cds** [comment]
Hi Andy, this makes sense.  I will have a go.  Thanks for pointing out :)

**Comment by Adnan-cds** [comment]
Hi Andy, I am about to start working on this.  Any suggestions for the migration group names?

**Comment by andybroomfield** [comment]
@Adnan-cds I would group it same as the menu link groups, so services, guides, step by steps, directories, campaigns (sub sites).

**Comment by Adnan-cds** [comment]
Thanks Andy.  I will let you know once this is ready.  Hopefully sometime tomorrow.
