### ISSUE TITLE
Migrated service status page has all updates on it

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_legacy_migration#6]
Since service status orignially uses entity que, all service status are being sent to the service-status page.

However the display looks jumbled up as so many status updates are all pulled together for each service.
This may actully be an issue to raise seperatly against localgov_services. However the issue here is that only service status that are intended for display on /service-status should be flagged to be placed their.

![Screenshot_2020-08-12 Service status Drush Site-Install](https://user-images.githubusercontent.com/1467480/90023702-efdd5680-dcab-11ea-82ac-0172c730405d.png)

**Comment by stephen-cox** [comment]
@andybroomfield The plan for statuses was to only have the relevant ones published. Would it be better to unpublish all service statuses when migrating them?

**Comment by finnlewis** [comment]
We think this is looking OK now: 
https://bhcc.localgov.agile.coop/service-status

**Comment by finnlewis** [comment]
@andybroomfield please re-open if still an issue.
